services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - go-net

  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - "9411:9411"
    networks:
      - go-net

  service-b-orchestration:
    build: ./service-b-orchestration
    ports:
      - "8081:8081"
    networks:
      - go-net
    env_file:
      - .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
      - VIA_CEP_URL=https://viacep.com.br/ws/
      - WEATHER_API_URL=https://api.weatherapi.com/v1/current.json
    depends_on:
      - otel-collector
      - zipkin

  service-a-input:
    build: ./service-a-input
    ports:
      - "8080:8080"
    networks:
      - go-net
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4318
      - SERVICE_B_URL=http://service-b-orchestration:8081
    depends_on:
      - service-b-orchestration
      - otel-collector
      - zipkin

networks:
  go-net:
